import { AppProps } from 'next/app';
import Head from 'next/head'
import React from 'react';

type headProps = {
    title : String;
}

const fixedTitle:String = 'wooklog'

function myHead(props:headProps){
    const title:String = `${props.title} | ${fixedTitle}` ;
    return (
                <Head>
                    <title>{title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
    )
}

export default myHead;