import styles from '/styles/Home.module.css'
import Head from 'next/head'
import Nav from './nav'
import {env_config} from '../../config/config'

export default function layout ({children}) {
    const title = children.type.name;
    return (
        <div className={styles.container}>
            <Head>
                <title>{title ? title : "wooklee"} | {env_config.mainFixTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
            <header>
                <Nav></Nav>
            </header>
            <main className={styles.main}>
                {children}
            </main>
            <footer className={styles.footer}>
                footer Component.
            </footer>
            </div>     
        </div>
    );
};